jobs:
   build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    - name: Test - Pre Deploy
      run: npm test:ci
    - name: Deploy
      run: |
        aws cloudformation deploy \
          --stack-name my-cool-stack \
          --template-file ./deploy/my-cool-stack.yaml \
    - name: Test - Post Deploy
      run: npm e2e:ci
